= Funciones
:revdate: 2026-03-05
:page-revdate: {revdate}

Esta sección describe las características y las fases de características en {product_name}.

== Lista de características

|===
| Función | Nombre de la característica de Helm | Subcaracterística | Default | Fase 

| *Proveedor de complemento para Fleet*
| `addon-provider-fleet`
| _ninguna._
| habilitado
| beta

| *Modo TLS del agente*
| `agent-tls-mode`
| _ninguna._
| habilitado
| beta

| *No Cert Manager*
| `no-cert-manager`
| _ninguna._
| habilitado
| beta

| *Usar el registro predeterminado de Rancher*
| `use-rancher-default-registry`
| _ninguna._
| habilitado
| beta

|===

=== Proveedor de complemento para Fleet
Esta función instala el Proveedor de complemento de la API de clúster (CAAPF) para Fleet para proporcionar integración con https://github.com/rancher/fleet[Fleet] y habilitar el despliegue fácil de aplicaciones en clústeres provisionados por CAPI. CAAPF instala automáticamente Fleet en el clúster de gestión y registra los clústeres CAPI recién provisionados con Fleet, de modo que las aplicaciones se puedan desplegar en estos clústeres a través de GitOps, `Bundle` o `HelmOp` recursos. CAAPF también incluye soporte para agrupar clústeres CAPI que hacen referencia a la misma ClusterClass a través del ClusterGroup de Fleet, simplificando esencialmente los despliegues de aplicaciones a grandes grupos de clústeres. Esta función está en fase de GA y habilitada por defecto.

=== Modo TLS del agente
Este gate de características se utiliza para instruir a Turtles sobre si debe seguir la configuración de `agent-tls-mode` de Rancher, al recuperar manifiestos de registro de clúster para importar clústeres. Cuando está habilitado, Turtles buscará el valor de la configuración de `agent-tls-mode` de Rancher para determinar si se ha establecido en `system-store` o `strict`. Si se establece en `system-store`, Turtles confiará en cualquier certificado generado por una Autoridad de Certificación pública contenida en el almacén de confianza del sistema operativo, incluidos aquellos firmados por autoridades como Let's Encrypt. Si se establece en `strict`, Turtles solo confiará en los certificados generados por la Autoridad de Certificación contenida en la configuración de `cacerts` de Rancher. Cuando esta configuración está deshabilitada, Turtles volverá a trabajar en modo `system-store`. Esta función está en fase beta y habilitada por defecto.

=== No Cert Manager
Este gate de características convierte los manifiestos de los proveedores de CAPI para reemplazar el uso de cert-manager con https://github.com/rancher/wrangler/[wrangler].

En particular, los webhooks de admisión de validación y mutación se actualizarán para utilizar certificados generados por wrangler, en lugar de cert-manager, permitiendo un entorno sin cert-manager.

Ten en cuenta que el uso de la `CATTLE_SYNC_ONLY_CHANGED_OBJECTS` https://documentation.suse.com/cloudnative/rancher-manager/latest/en/installation-and-upgrade/best-practices/tuning-rancher-at-scale.html#_reducing_event_handler_executions[funcionalidad] de Rancher puede impedir que los certificados se renueven después del tiempo de expiración predeterminado de un año.

Es posible desactivar esta función para restaurar todos los manifiestos de proveedores al uso original de cert-manager.

=== Usar el Registro Predeterminado de Rancher

Este gate de características instruye a {product_name} para aprovechar la configuración de gestión de `system-default-registry` de Rancher al construir referencias de imágenes para los componentes del proveedor de CAPI. Cuando está habilitado, {product_name} lee esta configuración y, si se ha configurado un registro, reescribe el repositorio para cada imagen de proveedor para utilizar ese registro.
Si la configuración está vacía, {product_name} vuelve a las referencias de imagen predeterminadas. Las sobreescrituras de imagen definidas en el recurso `ClusterctlConfig` siempre tienen prioridad. Para un uso detallado en un entorno aislado, consulta xref:operator/airgapped.adoc[Entorno aislado]. Esta función está en fase alfa y habilitada por defecto.

== Fases de características

{product_name} sigue el proceso https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-stages[de fases de características] de Kubernetes. Una característica puede estar en una de las siguientes fases: Alfa, Beta o Disponibilidad General (GA).

=== Fase Alfa
- Deshabilitada por defecto.
- Puede tener errores, sin soporte a largo plazo.
- La API puede cambiar sin previo aviso.
- Recomendado solo para clústeres de prueba de corta duración.

=== Fase Beta
- Siempre habilitado por defecto.
- Bien probado y considerado seguro.
- El soporte es estable, pero el esquema puede cambiar en futuras versiones.
- Recomendado para usos que no son críticos para el negocio debido a posibles cambios incompatibles.

[NOTE]
====
¡Por favor, proporciona comentarios sobre las características Alpha y Beta!
====

=== Fase de Disponibilidad General (GA)
- Siempre habilitado, no se puede desactivar.
- No se necesita gate de características.
- Estable, con soporte a largo plazo en futuras versiones.