version: 2

updates:
  - package-ecosystem: gitsubmodule
    schedule:
      interval: "daily"
    directory: /
  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      interval: "daily"
    labels:
      - "kind/cleanup"
      - "area/build-and-release"
