site:
  title: Rancher Turtles
  url: /
  start_page: v0.21@turtles:en:index.adoc

content:
  sources:
    - url: https://github.com/rancher/turtles-product-docs.git
      branches: [main]
      start_paths: [docs/v0.21, docs/v0.20, docs/v0.19, docs/v0.18, docs/v0.17, docs/v0.16, docs/v0.15, docs/v0.14, docs/v0.13, docs/v0.12, docs/v0.11]


# Description: SUSE UI bundle
ui:
  bundle:
    url: https://github.com/rancher/product-docs-ui/blob/main/build/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ./turtles-supplemental-files

runtime:
  fetch: true

asciidoc:
  attributes:
    build-type: community
    page-pagination: ''
    tabs-sync-option: ''
  extensions:
  - '@asciidoctor/tabs'
antora:
  extensions:
  - require: '@antora/lunr-extension'
  - require: '@springio/antora-xref-extension'