site:
  title: Rancher Turtles
  url: /
  start_page: v0.21@turtles:en:index.adoc

urls:
  latest_version_segment: stable
  latest_prerelease_version_segment: next

content:
  sources:
    - url: ./
      start_paths: [community-docs/v0.21, community-docs/v0.20, community-docs/v0.19, community-docs/v0.18, community-docs/v0.17, community-docs/v0.16, community-docs/v0.15, community-docs/v0.14, community-docs/v0.13, community-docs/v0.12, community-docs/v0.11, community-docs/next]
      branches: HEAD

# Description: SUSE UI bundle
ui:
  bundle:
    url: https://github.com/rancher/product-docs-ui/blob/main/build/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ./turtles-supplemental-files

asciidoc:
  attributes:
    page-pagination: ''
    page-toclevels: 4@
    tabs-sync-option: ''
  extensions:
    - '@asciidoctor/tabs'
antora:
  extensions:
  - require: '@antora/lunr-extension'

output:
  dir: build/site
