= プロバイダー認証 
:revdate: 2025-06-30
:page-revdate: {revdate}

== 認証されたプロバイダーとは何ですか？

ほとんどのCAPIプロバイダーはオープンコミュニティによって維持されているアップストリームプロジェクトであるため、特定のプロバイダーでプロビジョニングされたクラスターがTurtlesを介してRancherにインポートできることを保証する安全な方法はありません。ただし、次のようなプロバイダーに対しては認証プロセスを実施しています：

* E2Eテストスイートの一部として積極的にテストされています。
* プロバイダーの最近のバージョンを検証するために、このE2Eテストスイートを最新の状態に保っています。

== カスタムプロバイダーを認証する

さらに、プロバイダー開発者であるか、単に認証されていない別のプロバイダーを使用したい場合は、2つのオプションがあります：

* 既存のTurtles E2Eスイートを再利用して、認証ステータスリクエストを開始します。より詳細な情報は、xref:./certification.adoc#_provider_certification_using_turtles_test_suite[プロバイダー認証のためのTurtlesテストスイート]セクションにあります。
* 独自の統合スイートを使用してプロバイダーを認証します。より詳細な情報は、xref:./certification.adoc#_certify_provider_with_custom_integration_suite[カスタム統合スイートでのプロバイダー認証]セクションにあります。

[discrete]
==== *なぜプロバイダーを検証したいのですか？*

CAPIプロバイダーの数は増え続けており、コミュニティはさまざまなインフラストラクチャホストのための新しいプロジェクトを考案しています。このオープン性はCAPIエコシステムを豊かにしますが、TurtlesがCAPIプロジェクト全体で動作するすべてのプロバイダーを制御しテストすることは不可能です。Turtlesの開発者は、CIメカニズムによって積極的にテストされ検証されたxref:../overview/certified.adoc[認証されたプロバイダーのリスト]を維持しますが、このリストは主要でよく知られたプロバイダーに限られます。そのため、リストにないプロバイダーのユーザーには、Turtlesのテストスイートを再利用してプロバイダーとTurtlesの統合を検証することをお勧めします。

[discrete]
==== *認証されていないプロバイダーでTurtlesを使用できますか？*

Turtlesは、全体のCAPIエコシステムと統合することを目指すプロジェクトであり、プロバイダーを検証せずに自由に使用できます。ほとんどのアップストリームプロジェクトで問題が発生しない可能性が高いです。

[discrete]
==== *認証されたものとサポートされているものの違いは何ですか？*

CAPIプロバイダーはKubernetesコミュニティによって維持されているプロジェクトであるため、特定のプロバイダーに対するサポートを保証することはできません。このため、私たちはxref:../overview/certified.adoc[認証されたプロバイダー]の継続的な検証に焦点を当て、ユーザーが選択したプロバイダーを検証するために既存のテストスイートと統合する可能性を提供します。

== プロバイダー認証のためのTurtlesテストスイート

認証プロセスは、CAPIプロバイダーとの{product_name}統合を検証することに基づいています。この作業を簡素化するために、ダウンストリームのCAPIクラスターのプロビジョニングとインポートを検証する一般的なテストを準備しました。

[TIP]
====
Turtlesのテストスイートの使用方法については、このhttps://github.com/rancher-sandbox/turtles-integration-suite-example[例]を参照することをお勧めします。
====

=== プロバイダーをテストおよび認証する

あなたのプロバイダーがTurtlesと互換性があり、CAPIクラスターをプロビジョニングし、Turtlesを介してRancherにインポートできることを検証する最初のステップは、私たちのテストスイートと統合することです。あなたの統合の参考として使用できるhttps://github.com/rancher-sandbox/turtles-integration-suite-example[統合例]を含むリポジトリを提供します。

Turtlesは、異なる機能やプロセスを検証するためのhttps://github.com/rancher/turtles/tree/main/test/e2e/suites[複数のスイート]を含むプロジェクトですが、プロバイダー認証のためには、GitOpsフローを使用する1つのテストのみを実行する必要があります。Turtlesは、クラスターのプロビジョニングにGitOpsアプローチとよく統合されているプロジェクトであり、これがRancherとのプロバイダー統合を検証するための主な方法です。特定のCAPIプロバイダーのためにフルスイートを実行すると：

* 希望する環境に管理クラスターを作成します。
* すべての前提条件を持つRancherとTurtlesをインストールします。
* Giteaをインストールします。
* Gitリポジトリを作成し、Fleetを使用してクラスターのテンプレートを適用し、クラスターが作成され、Rancherに正常にインポートされたことを確認するスイートを実行します。

==== テスト構成

テストスイートを正常に実行するには、いくつかの環境変数を提供する必要があります。これらの中には無関係なものもあり、テストしたいプロバイダーに必要ですが、他のものは検証しているプロバイダーに特有のものになります。テストされているプロバイダーの特定の仕様、例えば資格情報やエンドポイントなどに注意してください。

[TIP]
====
次に、xref:../operator/certificationsuite.adoc[テストスイートガイド]をお読みいただくことをお勧めします。
====

== カスタム統合スイートでプロバイダーを認証する

カスタム統合スイートを使用してプロバイダーを認証するには、以下の主要な要件を満たしていることを確認してください。

=== 要件

* プロバイダーは`CAPIProvider` APIを使用してデプロイされなければなりません。
* プロバイダーで作成されたクラスターは、Turtlesを介してRancherに正常にインポートされなければなりません。

=== 認証プロセス

1. **統合スイートを開発する**
   * RancherとTurtlesをインストールして構成します。
   * CAPIプロバイダーをデプロイする。
   * クラスターをプロビジョニングし、それをRancherにインポートします。

2. **テストを実行して検証する**
   * クラスターが正常に作成され、インポートされていることを確認する。

3. **認証のリクエストを提出する**
   * テスト結果、ログ、および実行した手順を提供する。
   * 以下のhttps://github.com/rancher/turtles/issues/new?template=certification_request.yaml[テンプレート]を使用してGitHubの問題を提出する。

== 認証のリクエスト

Turtlesのテストスイートと統合し、関心のあるプロバイダーでチェックを実行することは、それが{product_name}と互換性があることを検証するのに十分です。すべてのCAPIプロバイダーを継続的にテストすることは現実的ではないため、この認証ワークフローにより、ユーザーとして期待される機能を検証できます。ただし、私たちは新しいバージョンのTurtlesを使用して新しいイテレーションのプロバイダーを積極的にテストしていないため、特定のプロバイダーに対するサポートと保証は限られており、将来のリリースの検証はあなたの責任となります。

プロバイダーのチェックを正常に実行した後、xref:../overview/certified.adoc[認証されたプロバイダー]のリストに追加し、プロジェクトの定期的なE2Eスイートに含めることを希望される場合は、https://github.com/rancher/turtles/issues/new?template=certification_request.yaml[認定リクエストテンプレート]を使用してGitHubの問題を提出することで認定をリクエストできます。コミュニティは提案をレビューし、プロバイダーを認定マトリックスに追加することの実現可能性を判断します。
