= Instalar proveedores certificados
:revdate: 2026-02-17
:page-revdate: {revdate}

Esta sección describe cómo instalar el gráfico de proveedores {product_name}, que instala los xref:overview/certified.adoc[proveedores certificados].

== Requisitos previos

* Asegúrate de que {product_name} ha sido instalado.

== Instala el {product_name} gráfico de proveedores

Para instalar todos los proveedores certificados, ejecuta el siguiente comando:

[source,shell]
----
helm install rancher-turtles-providers oci://<prime-registry-url>/rancher/charts/rancher-turtles-providers \
    --version <version> \
    --namespace cattle-turtles-system \
    --set providers.bootstrapKubeadm.enabled=true \
    --set providers.controlplaneKubeadm.enabled=true \
    --set providers.infrastructureDocker.enabled=true \
    --set providers.infrastructureAWS.enabled=true \
    --set providers.infrastructureAzure.enabled=true \
    --set providers.infrastructureGCP.enabled=true \
    --set providers.infrastructureGCP.variables.GCP_B64ENCODED_CREDENTIALS="" \
    --set providers.infrastructureVSphere.enabled=true \
    --set providers.bootstrapRKE2.enabled=true \
    --set providers.controlplaneRKE2.enabled=true \
    --set providers.addonFleet.enabled=true \
    --wait
----

El comando anterior se utiliza para instalar todos los proveedores certificados. Puedes personalizar qué proveedores se instalan configurando los flags relevantes a verdadero. Ten en cuenta que los proveedores CAPRKE2 y Fleet Addon están habilitados por defecto y se instalarán a menos que se deshabiliten explícitamente.

Por ejemplo, para poder aprovisionar clústeres RKE2 en AWS, solo necesitas instalar el proveedor de AWS de la siguiente manera:

[source,shell]
----
helm install rancher-turtles-providers oci://<prime-registry-url>/rancher/charts/rancher-turtles-providers \
    --version <version> \
    --namespace cattle-turtles-system \
    --set providers.infrastructureAWS.enabled=true \
    --set providers.infrastructureAWS.variables.AWS_B64ENCODED_CREDENTIALS=${AWS_B64ENCODED_CREDENTIALS} \
    --wait
----

Para poder aprovisionar clústeres RKE2 en Azure, solo instala el proveedor de Azure de la siguiente manera:

[source,shell]
----
helm install rancher-turtles-providers oci://<prime-registry-url>/rancher/charts/rancher-turtles-providers \
    --version <version> \
    --namespace cattle-turtles-system \
    --set providers.infrastructureAzure.enabled=true \
    --wait
----