= Zertifizierte Anbieter installieren
:revdate: 2026-02-17
:page-revdate: {revdate}

In diesem Abschnitt wird beschrieben, wie das {product_name} Providers-Chart installiert wird, das die xref:overview/certified.adoc[zertifizierten Anbieter] installiert.

== Voraussetzungen

* Stellen Sie sicher, dass {product_name} installiert wurde.

== Installieren Sie das {product_name} Providers-Chart

Um alle zertifizierten Anbieter zu installieren, führen Sie den folgenden Befehl aus:

[source,shell]
----
helm install rancher-turtles-providers oci://<prime-registry-url>/rancher/charts/rancher-turtles-providers \
    --version <version> \
    --namespace cattle-turtles-system \
    --set providers.bootstrapKubeadm.enabled=true \
    --set providers.controlplaneKubeadm.enabled=true \
    --set providers.infrastructureDocker.enabled=true \
    --set providers.infrastructureAWS.enabled=true \
    --set providers.infrastructureAzure.enabled=true \
    --set providers.infrastructureGCP.enabled=true \
    --set providers.infrastructureGCP.variables.GCP_B64ENCODED_CREDENTIALS="" \
    --set providers.infrastructureVSphere.enabled=true \
    --set providers.bootstrapRKE2.enabled=true \
    --set providers.controlplaneRKE2.enabled=true \
    --set providers.addonFleet.enabled=true \
    --wait
----

Der obige Befehl wird verwendet, um alle zertifizierten Anbieter zu installieren. Sie können anpassen, welche Anbieter installiert werden, indem Sie die entsprechenden Flags auf true setzen. Bitte beachten Sie, dass die Anbieter CAPRKE2 und Fleet Addon standardmäßig aktiviert sind und installiert werden, es sei denn, sie werden ausdrücklich deaktiviert.

Um beispielsweise RKE2-Cluster auf AWS bereitzustellen, müssen Sie nur den AWS-Anbieter wie folgt installieren:

[source,shell]
----
helm install rancher-turtles-providers oci://<prime-registry-url>/rancher/charts/rancher-turtles-providers \
    --version <version> \
    --namespace cattle-turtles-system \
    --set providers.infrastructureAWS.enabled=true \
    --set providers.infrastructureAWS.variables.AWS_B64ENCODED_CREDENTIALS=${AWS_B64ENCODED_CREDENTIALS} \
    --wait
----

Um RKE2-Cluster auf Azure bereitzustellen, installieren Sie einfach den Azure-Anbieter wie folgt:

[source,shell]
----
helm install rancher-turtles-providers oci://<prime-registry-url>/rancher/charts/rancher-turtles-providers \
    --version <version> \
    --namespace cattle-turtles-system \
    --set providers.infrastructureAzure.enabled=true \
    --wait
----