= Instalar provedores certificados
:revdate: 2026-02-17
:page-revdate: {revdate}

Esta seção descreve como instalar o gráfico de provedores {product_name}, que instala os xref:overview/certified.adoc[provedores certificados].

== Pré-requisitos

* Certifique-se de que {product_name} foi instalado.

== Instale o {product_name} gráfico de provedores

Para instalar todos os provedores certificados, execute o seguinte comando:

[source,shell]
----
helm install rancher-turtles-providers oci://<prime-registry-url>/rancher/charts/rancher-turtles-providers \
    --version <version> \
    --namespace cattle-turtles-system \
    --set providers.bootstrapKubeadm.enabled=true \
    --set providers.controlplaneKubeadm.enabled=true \
    --set providers.infrastructureDocker.enabled=true \
    --set providers.infrastructureAWS.enabled=true \
    --set providers.infrastructureAzure.enabled=true \
    --set providers.infrastructureGCP.enabled=true \
    --set providers.infrastructureGCP.variables.GCP_B64ENCODED_CREDENTIALS="" \
    --set providers.infrastructureVSphere.enabled=true \
    --set providers.bootstrapRKE2.enabled=true \
    --set providers.controlplaneRKE2.enabled=true \
    --set providers.addonFleet.enabled=true \
    --wait
----

O comando acima é usado para instalar todos os provedores certificados. Você pode personalizar quais provedores são instalados definindo as flags relevantes como verdadeiras. Observe que os provedores CAPRKE2 e Fleet Addon estão habilitados por padrão e serão instalados, a menos que sejam explicitamente desabilitados.

Por exemplo, para poder provisionar clusters RKE2 na AWS, você só precisa instalar o provedor AWS da seguinte forma:

[source,shell]
----
helm install rancher-turtles-providers oci://<prime-registry-url>/rancher/charts/rancher-turtles-providers \
    --version <version> \
    --namespace cattle-turtles-system \
    --set providers.infrastructureAWS.enabled=true \
    --set providers.infrastructureAWS.variables.AWS_B64ENCODED_CREDENTIALS=${AWS_B64ENCODED_CREDENTIALS} \
    --wait
----

Para poder provisionar clusters RKE2 no Azure, basta instalar o provedor Azure da seguinte forma:

[source,shell]
----
helm install rancher-turtles-providers oci://<prime-registry-url>/rancher/charts/rancher-turtles-providers \
    --version <version> \
    --namespace cattle-turtles-system \
    --set providers.infrastructureAzure.enabled=true \
    --wait
----