= Certificación de Proveedores 
:revdate: 2025-06-30
:page-revdate: {revdate}

== ¿Qué es un Proveedor Certificado?

Como la mayoría de los proveedores de CAPI son proyectos en sentido ascendente mantenidos por la comunidad abierta, no hay una forma segura de garantizar que cualquier clúster provisionado con un proveedor dado pueda ser importado a Rancher a través de Turtles. Sin embargo, implementamos un proceso de certificación para aquellos proveedores que son:

* Probados activamente como parte de nuestra suite de pruebas E2E.
* Mantenida esta suite de pruebas E2E actualizada para validar las versiones recientes del proveedor.

== Certifica tu Proveedor Personalizado

Además, si eres un desarrollador de proveedores o simplemente quieres usar un proveedor diferente que no esté listado como certificado, tienes 2 opciones:

* Reutiliza la suite E2E existente de Turtles para comenzar con la solicitud de estado de certificación. Más información detallada se puede encontrar aquí en la sección xref:./certification.adoc#_provider_certification_using_turtles_test_suite[Certificación de Proveedores Usando la Suite de Pruebas de Turtles].
* Usa tu propia suite de integración para certificar tu proveedor. Más información detallada se puede encontrar aquí en la sección xref:./certification.adoc#_certify_provider_with_custom_integration_suite[Certificar Proveedor Con Suite de Integración Personalizada].

[discrete]
==== *¿Por qué querría validar mi proveedor?*

El número de proveedores de CAPI sigue creciendo y la comunidad está creando nuevos proyectos para diferentes hosts de infraestructura. Esta apertura ayuda a enriquecer el ecosistema de CAPI, pero hace imposible controlar y probar todos los proveedores con los que Turtles funcionará en todo el proyecto CAPI. Los desarrolladores de Turtles mantendrán una xref:../overview/certified.adoc[lista de proveedores certificados] que son probados y validados activamente por mecanismos de CI, pero esta lista estará limitada a proveedores clave y bien conocidos. Por eso animamos a los usuarios de proveedores no listados a reutilizar la suite de pruebas de Turtles y validar la integración entre el proveedor y Turtles.

[discrete]
==== *¿Puedo usar Turtles con un proveedor no certificado?*

Turtles es un proyecto que tiene como objetivo ser agnóstico e integrarse con todo el ecosistema de CAPI y eres libre de usarlo sin validar ningún proveedor. Es probable que no encuentres problemas con la mayoría de los proyectos en sentido ascendente.

[discrete]
==== *¿Cuál es la diferencia entre certificado y soportado?*

Dado que los proveedores de CAPI son proyectos mantenidos por la comunidad de Kubernetes, no podemos garantizar soporte para un proveedor determinado. Por eso optamos por centrarnos en la validación constante de xref:../overview/certified.adoc[Proveedores Certificados] y ofrecer a los usuarios la posibilidad de integrarse con la suite de pruebas existente para verificar sus proveedores elegidos.

== Certificación de Proveedores Usando la Suite de Pruebas de Turtles

El proceso de certificación se basa en verificar la integración de {product_name} con los proveedores de CAPI. Para simplificar esta tarea, hemos preparado una prueba genérica que valida el aprovisionamiento e importación de un clúster CAPI en sentido descendente.

[TIP]
====
Te recomendamos que consultes este https://github.com/rancher-sandbox/turtles-integration-suite-example[ejemplo] sobre cómo usar la suite de pruebas de Turtles.
====

=== Prueba y Certifica Tu Proveedor

El primer paso para validar que tu proveedor es compatible con Turtles y que puedes aprovisionar clústeres CAPI e importarlos en Rancher a través de Turtles es integrarte con nuestra suite de pruebas. Proporcionamos un repositorio con un https://github.com/rancher-sandbox/turtles-integration-suite-example[ejemplo de integración] que puedes usar como referencia para tu integración.

Turtles, como proyecto, contiene un https://github.com/rancher/turtles/tree/main/test/e2e/suites[número de suites] para verificar diferentes características y procesos, pero, para la certificación de proveedores, requerimos que ejecutes solo una prueba que utilice un flujo de GitOps. Turtles es un proyecto que se integra bien con un enfoque de GitOps para el aprovisionamiento de clústeres y por eso esta es nuestra forma principal de validar la integración del proveedor con Rancher. Ejecutar la suite completa para un proveedor de CAPI dado hará:

* Crear un clúster de gestión en el entorno deseado.
* Instalar Rancher y Turtles con todos los prerrequisitos.
* Instalar Gitea.
* Ejecutar la suite que creará un repositorio git, aplicará la plantilla del clúster usando Fleet y verificará que el clúster se crea e importa correctamente en Rancher.

==== Configuración de pruebas

Para ejecutar con éxito la suite de pruebas, tendrás que proporcionar una serie de variables de entorno. Algunos de estos son agnósticos, lo que significa que son necesarios para cualquier proveedor que desees probar, pero otros serán específicos para el proveedor que estás validando. Por favor, ten en cuenta las especificaciones particulares del proveedor que se está probando, como credenciales, puntos finales, etc.

[TIP]
====
A continuación, te recomendamos que leas la xref:../operator/certificationsuite.adoc[guía de la suite de pruebas].
====

== Certificar Proveedor Con Suite de Integración Personalizada

Para certificar tu proveedor utilizando una suite de integración personalizada, asegúrate de que cumpla con los siguientes requisitos clave:

=== Requisitos

* El proveedor debe estar desplegado utilizando `CAPIProvider` la API.
* Los clústeres creados con el proveedor deben ser importados con éxito en Rancher a través de Turtles.

=== Proceso de certificación

1. **Desarrollar una Suite de Integración** 
   * Instala y configura Rancher y Turtles.
   * Despliega el proveedor CAPI.
   * Aprovisiona un clúster e impórtalo en Rancher.

2. **Ejecutar y Validar Pruebas**
   * Asegúrate de que los clústeres se creen e importen con éxito.

3. **Enviar una solicitud de Certificación**
   * Proporciona resultados de pruebas, registros y pasos seguidos.
   * Envía un problema en GitHub utilizando la siguiente https://github.com/rancher/turtles/issues/new?template=certification_request.yaml[plantilla].

== Solicitud de Certificación

Integrarse con la suite de pruebas de Turtles y realizar verificaciones en tu proveedor de interés es suficiente para validar que es compatible con {product_name}. Como no es factible para nosotros probar continuamente cada proveedor CAPI, este flujo de trabajo de certificación te permitirá, como usuario, verificar la funcionalidad esperada. Sin embargo, como no estamos probando activamente iteraciones más nuevas del proveedor (con versiones más nuevas de Turtles), el soporte y la garantía para el proveedor dado son limitados, y serás responsable de validar futuras versiones.

Si, después de realizar con éxito las comprobaciones en tu proveedor, deseas solicitar que se añada a la lista de xref:../overview/certified.adoc[Proveedores Certificados] e incluirlo en la suite E2E periódica del proyecto, puedes solicitar la certificación presentando un problema en GitHub utilizando la https://github.com/rancher/turtles/issues/new?template=certification_request.yaml[plantilla de Solicitud de Certificación]. La comunidad revisará la propuesta y determinará la viabilidad de añadir el proveedor a la matriz de certificación.
