= Installer des fournisseurs certifiés
:revdate: 2026-02-17
:page-revdate: {revdate}

Cette section décrit comment installer le {product_name} Providers chart, qui installe les xref:overview/certified.adoc[fournisseurs certifiés].

== Conditions préalables

* Assurez-vous que {product_name} a été installé.

== Installer le {product_name} Providers chart

Pour installer tous les fournisseurs certifiés, exécutez la commande suivante :

[source,shell]
----
helm install rancher-turtles-providers oci://<prime-registry-url>/rancher/charts/rancher-turtles-providers \
    --version <version> \
    --namespace cattle-turtles-system \
    --set providers.bootstrapKubeadm.enabled=true \
    --set providers.controlplaneKubeadm.enabled=true \
    --set providers.infrastructureDocker.enabled=true \
    --set providers.infrastructureAWS.enabled=true \
    --set providers.infrastructureAzure.enabled=true \
    --set providers.infrastructureGCP.enabled=true \
    --set providers.infrastructureGCP.variables.GCP_B64ENCODED_CREDENTIALS="" \
    --set providers.infrastructureVSphere.enabled=true \
    --set providers.bootstrapRKE2.enabled=true \
    --set providers.controlplaneRKE2.enabled=true \
    --set providers.addonFleet.enabled=true \
    --wait
----

La commande ci-dessus est utilisée pour installer tous les fournisseurs certifiés. Vous pouvez personnaliser les fournisseurs installés en définissant les indicateurs pertinents à true. Notez que les fournisseurs CAPRKE2 et Fleet Addon sont activés par défaut et seront installés à moins d'être explicitement désactivés.

Par exemple, pour pouvoir provisionner des clusters RKE2 sur AWS, vous devez simplement installer le fournisseur AWS comme suit :

[source,shell]
----
helm install rancher-turtles-providers oci://<prime-registry-url>/rancher/charts/rancher-turtles-providers \
    --version <version> \
    --namespace cattle-turtles-system \
    --set providers.infrastructureAWS.enabled=true \
    --set providers.infrastructureAWS.variables.AWS_B64ENCODED_CREDENTIALS=${AWS_B64ENCODED_CREDENTIALS} \
    --wait
----

Pour pouvoir provisionner des clusters RKE2 sur Azure, il suffit d'installer le fournisseur Azure comme suit :

[source,shell]
----
helm install rancher-turtles-providers oci://<prime-registry-url>/rancher/charts/rancher-turtles-providers \
    --version <version> \
    --namespace cattle-turtles-system \
    --set providers.infrastructureAzure.enabled=true \
    --wait
----