= ClusterctlConfig
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-11-14
:page-revdate: {revdate}

O recurso `ClusterctlConfig` permite gerenciar substituiĂ§Ăµes para as configuraĂ§Ăµes do clusterctl (Operador CAPI) de forma declarativa. Ă‰ usado para configurar provedores do clusterctl e suas URLs, bem como restriĂ§Ăµes de versĂŁo.

`ClusterctlConfig` segue um modelo GitOps - os campos da especificaĂ§ĂŁo sĂŁo entradas de usuĂˇrio declarativas. O Turtles nĂŁo cria ou atualiza o recurso, cabe ao usuĂˇrio especificar as substituiĂ§Ăµes de URL do provedor e manter seu estado. Ele tem precedĂŞncia sobre os padrĂµes embutidos ou `clusterctl` o conjunto padrĂŁo de definiĂ§Ăµes de provedores.

https://github.com/rancher/turtles/blob/main/docs/adr/0012-clusterctl-provider.md[ADR]

== Uso

Para usar o recurso `ClusterctlConfig`:

. Crie um recurso `ClusterctlConfig` com o nome `clusterctl-config` no namespace `turtles`.
. O controlador `ClusterctlConfig` lidarĂˇ com as atualizaĂ§Ăµes para o `ConfigMap` montado no ponto de montagem `cluster-api-operator` com a configuraĂ§ĂŁo de clusterctl necessĂˇria com base na especificaĂ§ĂŁo `ClusterctlConfig`.
. Gerencie o objeto `ClusterctlConfig` de forma declarativa para aplicar alteraĂ§Ăµes Ă s configuraĂ§Ăµes de provedores geradas. Pode levar algum tempo para que as alteraĂ§Ăµes tenham efeito, jĂˇ que `kubelet` cuida de atualizar o ponto de montagem com base no estado de `ConfigMap`.

Aqui estĂˇ um exemplo de manifesto `ClusterctlConfig`:

[,yaml]
----
apiVersion: turtles-capi.cattle.io/v1alpha1
kind: ClusterctlConfig
metadata:
  name: clusterctl-config
  namespace: cattle-turtles-system
spec:
  providers:
  - name: metal3
    url: https://github.com/metal3-io/cluster-api-provider-metal3/releases/v1.10.1/infrastructure-components.yaml
    type: InfrastructureProvider
  images:
  - name: metal3
    repository: "my.registry.mirror"
    tag: customTag
----

Este exemplo gerarĂˇ uma configuraĂ§ĂŁo de clusterctl para o provedor `metal3` com a URL e tipo especificados.

== EspecificaĂ§ĂŁo

Os campos-chave na especificaĂ§ĂŁo `ClusterctlConfig` sĂŁo:

* `providers[].name` - Nome do provedor (por exemplo, Metal3)
* `providers[].url` - URL da configuraĂ§ĂŁo do provedor (por exemplo,
https://github.com/metal3-io/cluster-api-provider-metal3/releases/v1.10.1/infrastructure-components.yaml). Isso pode usar a versĂŁo `latest`, se suportada, ou fixar a versĂŁo mĂˇxima em `v1.10.1`, por exemplo.
* `providers[].type` - Tipo do provedor (por exemplo, InfrastructureProvider)

* `images[].name` - O nome da imagem a ser substituĂ­da (por exemplo, infrastructure-metal3, cluster-api, bootstrap-rke2, control-plane-rke2)
* `images[].repository` - Define a substituiĂ§ĂŁo do registro de contĂŞiner para puxar imagens de
* `images[].tag` - Permite especificar uma tag para as imagens

== Substituir uma versĂŁo de Provedor Certificado

{product_name} incorpora uma configuraĂ§ĂŁo validada onde todas as versĂµes de provedores certificados estĂŁo fixadas. +
Normalmente, as versĂµes sĂŁo atualizadas com qualquer lanĂ§amento de {product_name}.

[WARNING]
====
- {product_name} apenas valida a configuraĂ§ĂŁo incorporada para provedores certificados. Qualquer personalizaĂ§ĂŁo na configuraĂ§ĂŁo incorporada pode eventualmente levar a incompatibilidades e cenĂˇrios nĂŁo suportados. 
====

Para substituir uma versĂŁo de provedor ou usar um registro diferente para puxar imagens, um `ClusterctlConfig` pode ser definido. +
Para mais informaĂ§Ăµes sobre a substituiĂ§ĂŁo de imagens, consulte a link:https://cluster-api.sigs.k8s.io/clusterctl/configuration#image-overrides[documentaĂ§ĂŁo] upstream.

[source,yaml]
----
apiVersion: turtles-capi.cattle.io/v1alpha1
kind: ClusterctlConfig
metadata:
  name: clusterctl-config
  namespace: cattle-turtles-system
spec:
  providers:
  - name: rke2
    url: "https://github.com/rancher/cluster-api-provider-rke2/releases/v0.20.1/control-plane-components.yaml"
    type: ControlPlaneProvider
  - name: rke2
    url: "https://github.com/rancher/cluster-api-provider-rke2/releases/v0.20.1/bootstrap-components.yaml"
    type: BootstrapProvider
  images:
  - name: control-plane-rke2
    repository: "ghcr.io/rancher"
  - name: bootstrap-rke2
    repository: "ghcr.io/rancher"
----

== ExclusĂŁo

Quando um recurso `ClusterctlConfig` Ă© excluĂ­do, o mapa de configuraĂ§ĂŁo Ă© revertido para seu estado original, gerenciado por Turtles.