= Guía de migración
:revdate: 2025-11-14
:page-revdate: {revdate}

== Contexto

A partir de Rancher v2.13, {product_name} se instala como parte de Rancher, eliminando la necesidad de una ampliación separada. Antes de actualizar a Rancher v2.13, los usuarios deben seguir esta guía para asegurar un proceso de actualización de versión fluido.

== Migración

Sigue los pasos a continuación en orden, _antes_ de actualizar a Rancher v2.13:

. Asegúrate de actualizar {product_name} a v0.24.3. Este paso es importante porque todas las versiones de parche para v0.24 preparan el clúster para la actualización a Rancher v2.13.
. Desinstala {product_name}. Esto es necesario porque a partir de Rancher v2.13, {product_name} ya no es un complemento opcional, sino un componente del sistema de Rancher. Como tal, Rancher lo instala en un espacio de nombres diferente al anterior y, por lo tanto, la versión instalada previamente debe desinstalarse manualmente primero. Desinstalar v0.24.3 de {product_name} elimina el proveedor CAPI del kernel, pero mantiene los CRD CAPI. Durante la migración, el controlador CAPI del kernel no estará en funcionamiento en el clúster de gestión, pero cualquier clúster CAPI descendente debería seguir funcionando como de costumbre y no verse afectado.
. Ejecuta los siguientes comandos de kubectl:
+
[source,bash]
----
kubectl patch crd capiproviders.turtles-capi.cattle.io --type=json -p='[{"op": "add", "path": "/metadata/annotations/meta.helm.sh~1release-namespace", "value": "cattle-turtles-system"}]'
kubectl patch crd clusterctlconfigs.turtles-capi.cattle.io --type=json -p='[{"op": "add", "path": "/metadata/annotations/meta.helm.sh~1release-namespace", "value": "cattle-turtles-system"}]'
----

Estos comandos parchearán los CRD de `capiprovider` y `clusterctlconfig` para que sean adoptados por {product_name} cuando se instalen como parte de Rancher v2.13. 

Ten en cuenta que la migración descrita anteriormente es necesaria para los usuarios que ejecutan versiones de {product_name} &le; v0.24.3. Los nuevos usuarios que están instalando Rancher v2.13 no necesitan realizar ninguna migración.